config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'contacts#index'
  resources :contacts do #, only: [:index, :new, :create, :destroy, :edit, :update, :show]
    resources :comments, only: :create
    collection do
      get 'search'
    end
  end
  resources :users, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :contact
  belongs_to :user
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :text, presence: true
  belongs_to :user
  has_many :comments

  def self.search(search)
    return Contact.all unless search
    Contact.where('text LIKE(?)',"%#{search}%")
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :contacts
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
    #deviseでのnickname保存の許可
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    comment = Comment.create(comment_params)
    redirect_to "/contacts/#{comment.contact.id}"
  end

  private
  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, contact_id: params[:contact_id])
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:edit, :show]
  before_action :move_to_index, except: [:index, :show, :search]#リファクタリング+index,show,search以外は未ログインでは見れない

  def index
    @contacts = Contact.includes(:user).order("created_at DESC").page(params[:page]).per(5)
  end

  def new
    @contact = Contact.new
  end

  def create
    Contact.create(contact_params)
  end

  def edit
  end

  def update
    contact = Contact.find(params[:id])
    contact.update(contact_params)
  end

  def show
    @comment = Comment.new
    @comments = @contact.comments.includes(:user)
  end

  def search
    @contacts = Contact.search(params[:keyword])
  end

  def destroy
    contact = Contact.find(params[:id])
    contact.destroy
  end

  private
  def contact_params
    params.require(:contact).permit(:image, :text).merge(user_id: current_user.id)
  end

  def set_contact
    @contact =Contact.find(params[:id])
  end

  def move_to_index
    redirect_to action: :index unless user_signed_in?
    #ログインしていなければindex移行する
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    user = User.find(params[:id])
    @nickname = user.nickname
    @contacts = user.contacts.order("created_at DESC").page(params[:page]).per(5)
    #コメント欄に表示されるユーザー名をクリックすることで送られたidをparamsで取得して、そのユーザーのレコードを変数userに代入
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/contacts/_contact.html.erb
<div class="content_post" style="background-image: url(<%= contact.image %>);">
  <div class="more">
      <span><%= image_tag 'arrow_top.png' %></span>
        <ul class="more_list">
          <li>
            <%= link_to '詳細', "/contacts/#{contact.id}", method: :get%>
        <% if user_signed_in? && current_user.id == contact.user_id %>
          </li>  <!--ログイン中かつ投稿者IDが同じなら表示される↓-->
          <li>
            <%= link_to '編集', "/contacts/#{contact.id}/edit", method: :get %>
          </li>
          <li>
            <%= link_to '削除', "/contacts/#{contact.id}", method: :delete %>
          </li>
        <% end %>
        </ul>
  </div>
  <%= simple_format(contact.text)%>
  <span class="name">
    <a href="/users/<%= contact.user.id %>">
      <span>投稿者</span><%= contact.user.nickname %>
    </a>
  </span>
</div>

app/views/contacts/_form.html.erb
    <%= form.text_field :image, placeholder: "画像URL" %>
    <%= form.text_area :text, placeholder: "メッセージ入力", rows: "10" %>
    <%= form.submit "投稿する" %>

app/views/contacts/create.html.erb
<div class="contents row">
  <div class="success">
    <h3>
      投稿が完了しました。
    </h3>
    <a class="btn" href="/contacts">投稿一覧へ戻る</a>
  </div>
</div>

app/views/contacts/destroy.html.erb
<div class="contents row">
  <div class="success">
    <h3>
      削除が完了しました。
    </h3>
    <a class="btn" href="/">投稿一覧へ戻る</a>
  </div>
</div>

app/views/contacts/edit.html.erb
<div class="contents row">
  <div class="container">
    <%= form_with(model: @contact, local: true) do |form|%>
    <h3>
      編集ページ
    </h3>
      <%= render partial: "form", locals: { form: form } %>
    <% end %>
  </div>
</div>

app/views/contacts/index.html.erb
<div class = "contents row">
  <% @contacts.each do |contact| %>
    <%= render partial: "contact", locals: { contact: contact} %>
  <% end %>
  <%= paginate(@contacts) %>
</div>

app/views/contacts/new.html.erb
<div class="contents row">
  <div class="container">
    <%= form_with(model: @contact, local: true) do |form|%><!--contactsかも-->
    <h3>
      投稿ページ
    </h3>
      <%= render partial: "form", locals: { form: form } %>
    <% end %>
  </div>
</div>

app/views/contacts/search.html.erb
<%= form_with(url: search_contacts_path, local: true, method: :get, class: "search-form") do |form| %>
  <%= form.text_field :keyword, placeholder: "投稿を検索する", class: "search-input" %>
  <%= form.submit "検索", class: "search-btn" %>
<% end %>
<div class="contents row">
  <% @contacts.each do |contact| %>
    <%= render partial: "contact", locals: { contact: contact } %>
  <% end %>
</div>

app/views/contacts/show.html.erb
<div class ="contents row">
  <div class="content_post" style="background-image: url(<%= @contact.image %>);">
    <% if user_signed_in? && current_user.id == @contact.user_id %>
      <div class="more">
        <span><%= image_tag 'arrow_top.png' %></span>
        <ul class="more_list">
          <li>
            <%= link_to '編集', "/contacts/#{@contact.id}/edit", method: :get %>
          </li>
          <li>
            <%= link_to '削除', "/contacts/#{@contact.id}", method: :delete %>
          </li>
        </ul>
      </div>
    <% end %>
    <%= simple_format(@contact.text) %>
    <span class="name">
      <a href="/users/<%= @contact.user.id %>">
        <span>投稿者</span><%= @contact.user.nickname %>
      </a>
    </span>
  </div>
  <div class="container">
    <% if current_user %>
      <%= form_with(model: [@contact, @comment], local: true) do |form| %>
        <%= form.text_area :text, placeholder: "コメントする", rows: "2" %>
        <%= form.submit "送信" %>
      <% end %>
    <% else %>
      <strong><p>※※※ コメントの投稿には新規登録/ログインが必要です ※※※</p></strong>
    <% end %>
    <div class="comments">
      <h4>＜コメント一覧＞</h4>
      <% if @comments %>
        <% @comments.each do |comment| %>
          <p>
            <strong><%= link_to comment.user.nickname, "/users/#{comment.user_id}" %>：</strong>
            <%= comment.text %>
          </p>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/contacts/update.html.erb
<div class="contents row">
  <div class="success">
    <h3>
      更新が完了しました。
    </h3>
    <a class="btn" href="/">投稿一覧へ戻る</a>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pictweet</title>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <script type="text/javascript">
      WebFontConfig = {
        google: { families: [ 'Unica+One::latin' ] }
      };
      (function() {
        var wf = document.createElement('script');
        wf.src = ('https:' == document.location.protocol ? 'https' : 'http') +
          '://ajax.googleapis.com/ajax/libs/webfont/1/webfont.js';
        wf.type = 'text/javascript';
        wf.async = 'true';
        var s = document.getElementsByTagName('script')[0];
        s.parentNode.insertBefore(wf, s);
      })();
    </script>
  </head>

  <body>
    <header class="header">
      <div class="header__bar row">
        <h1 class="grid-6"><a href="/">PicTweet</a></h1>
        <% if user_signed_in? %>
          <div class="user_nav grid-6">  <!--ログインしている状態-->
            <span><%= current_user.nickname %>
            <ul class="user__info">
              <li>
                <%= link_to "マイページ", "/users/#{current_user.id}" %>
                <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
              </li>
            </ul>
          </span>
          <%= link_to "投稿する", "/contacts/new",class: "post" %>
        </div>
        <% else %>
          <div class="grid-6">>  <!--ログインしていない状態-->
            <%= link_to "ログイン", new_user_session_path, class: 'post' %>
            <%= link_to "新規登録", new_user_registration_path, class: 'post' %>
          </div>
        <% end %>
      </div>
    </header>

    <%= yield %>

    <footer>
      <p>
        PicTweet 2020.
      </p>
    </footer>
  </body>
</html>

app/views/users/show.html.erb
<div class="contents row">
  <p><%= @nickname %>さんの投稿一覧</p>

  <% @contacts.each do |contact| %>
    <%= render partial: "contacts/contact", locals: {contact: contact} %>
  <% end %>
    <%= paginate(@contacts) %>
</div>